server:
  port: 8443
  http:
    port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/speedgame.p12
    key-store-password: speedgame123
    key-alias: speedgame

spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    templateResolverOrder: 1
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/ratings-h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update